Repository embroider-build/content-tag, pull requests merged in 2024-02, with the labels that each got.

#63 Update docs with API changes
  README.md
Labels: documentation

#64 Update type declaration file with latest API
  index.d.ts
Labels: bug

#67 Fix sourcemap test
  test/process.test.js
Labels: internal

#69 Refactor options handling
  pkg/node.cjs
  pkg/standalone.js
  src/bindings.rs
Labels: internal
